### ISSUE TITLE
Notification pop-up in Geary barely legible in light variant

### ISSUE THREAD

**Issue by Nipsi** [Zaedus/Pop-nord#1]
**Describe the problem:**
The text in the notification pop-up inside of Geary after sending or tagging emails is too bright in the light variant of the theme.
![pop-nord-geary-censored](https://user-images.githubusercontent.com/8134686/103030373-f46c2280-455b-11eb-9f59-f8f5ca4ea53e.png)
I hope my bad censoring attempts don't hide the issue, but you can see the "Email to" and the text in the button on the right being barely legible.

**Distribution:**
Pop!_OS 20.10

P.S. Thanks for the awesome work!

**Comment by sleepforlife** [comment]
same here
pls fix

**Comment by Zaedus** [comment]
Sorry for the late response, I've noticed this too, and I'm trying to figure out what element that actually is so that I can, well, style it. I'm asking around currently, but hoping to have a fix within 24 hours. Thanks for your patience and support for this project :D

**Comment by Zaedus** [comment]
![image](https://user-images.githubusercontent.com/42098470/103179324-71471700-4850-11eb-8657-41f65f2f2620.png)
I believe the issue is fixed. Let me know if it works. I'm going to push the changes to gnome look soon, so for the time being just build it via the instructions in the readme.

**Comment by Nipsi** [comment]
Yup, looks good!
