### ISSUE TITLE
COSMIC desktop interferes with top bar

### ISSUE THREAD

**Issue by JasperEdits** [Zaedus/Pop-nord#4]
**Describe the problem:**
Visual artifact in top bar buttons.
![image](https://user-images.githubusercontent.com/28309837/123546667-e2af4600-d75d-11eb-8926-fa6d6d441f1b.png)

**Distribution:**
Pop!_OS 21.04

**Comment by JasperEdits** [comment]
This appears not to be a COSMIC issue after further testing.

**Comment by Zaedus** [comment]
I believe this issue is fixed after the latest release, but if this issue still persists please reopen this issue.
