### ISSUE TITLE
Application section without background and not displaying correctly

### ISSUE THREAD

**Issue by JasperEdits** [Zaedus/Pop-nord#5]
**Describe the problem:**
Applications section not displaying correctly.
![Peek 2021-06-27 15-52](https://user-images.githubusercontent.com/28309837/123547147-d7f5b080-d75f-11eb-85e0-4f87826f47c2.gif)

**Distribution:**
Pop!_OS 21.04

**Comment by protodrew** [comment]
Seconding this, scrolling also breaks it

**Comment by Zaedus** [comment]
Hello! Since this was made pre-cosmic everything does sort of break. However, I'll be trying to update the theme within the coming days.

**Comment by Zaedus** [comment]
Hello again! I just want to check back with you and see if your issue was fixed in the latest release, version v2.0.0. I believe I know what was causing your issue here, but I just want to make sure that what I did fixed it, so if the problem still persists please reopen this issue.

**Comment by ghost** [comment]
works perfectly now thank you so much!!!
