### ISSUE TITLE
COSMIC dock does not use the theme

### ISSUE THREAD

**Issue by tmpr** [Zaedus/Pop-nord#6]
Pretty simple issue, which might be either a Pop or a problem with the theme: The color of the dock stays in the typical Pop-grey.

![image](https://user-images.githubusercontent.com/51313597/124162991-68552d80-da9f-11eb-84b4-f9ee9a3899ce.png)

Thank you!

**Comment by Zaedus** [comment]
Hello! It has been awhile since I've updated the theme or even used Pop, but I will try to update it along with the cosmic desktop within the coming days.

**Comment by Zaedus** [comment]
I just released version 2.0.0, and I'm positive this is fixed, but please reopen the issue if the problem still persists.
